### ISSUE TITLE
.babelrc references emotion even when it's turned off during setup

### ISSUE THREAD

**Issue by revelt** [egoist/template-next#1]
Hi!

When I installed the next template, I chose no `emotion`. However, the installed `.babelrc` still mentioned it as a plugin and build was failing until I removed it:

```babelrc
{
  "presets": [
    "next/babel"
  ],
  "plugins": []
}
```

After that, build rendered fine.

I started investigating and what's strange, when I looked into the source of this repo, I couldn't find the `.babelrc` setup code... Please look into it, I'm not able to find the issue location and PR.

And thank you for this tool! 👍

**Comment by egoist** [comment]
Ah yeah I noticed this bug a while ago but haven't got time to fix it 😅  sorry for the trouble, I will fix it later.
